server:
  port: 8091
spring:
  application:
    name: microservice-movie
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8181/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
